#客户请求distributed-security-uaa授权服务申请access_token
server:
  port: 8300
  servlet:
    context-path: /

spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
